// As receitas dos estados (G21): de que caso ou dado do mock cada estado
// nasce. `casos` são chaves de M.casos; `dados`, caminhos de M. Onde nada no
// mock produz o estado, a receita diz `aditivo` — o caso entra no ciclo da
// tela (G8). Cada ciclo de tela completa as receitas das suas telas.
export const RECEITAS = {
  'T01/01-estado-usuario-ou-senha-incorretos': { dados: ['credenciais'] },
  'T01/06-estado-codigo-expirado': { dados: ['credenciais.recuperacao.limites.validadeMin'] },
  'T01/07-estado-tentativas-esgotadas': { dados: ['credenciais.recuperacao.limites.tentativas'] },
  'T01/14-estado-login-sem-conexao': { casos: ['sem-conexao-no-login'], obs: 'o Entrar sem internet: o aviso, e os campos ficam preenchidos (entrega do design de 25/09, o mundo real)' },
  'T01/15-estado-primeiro-acesso': { casos: ['primeiro-acesso'], obs: 'nada lembrado: os dois campos vazios, o foco no usuário, e o Entrar diz Digite o usuário (a otimização do design, 25/09)' },
  'T01/16-estado-usuario-lembrado': { casos: ['usuario-lembrado'], obs: 'o r.vieira lembrado, com o xis, a caixa marcada e o foco na senha (a otimização do design, 25/09)' },
  'T01/17-estado-teto-de-envios': { casos: ['teto-de-envios'], dados: ['credenciais.recuperacao.limites.tetoPorHora'], obs: 'os 3 envios da hora acabaram: o código do mock enviado segue valendo, e a linha diz até quando, pela hora do caso (a última entrega, HU-T01-7)' },
  'T01/18-estado-outro-usuario-no-aparelho': { casos: ['outro-usuario'], dados: ['ucs', 'uos', 'pacotes'], obs: 'as unidades da T02 com o diálogo Outra sessão neste aparelho: a sessão do r.vieira encerrada, e a fila dele, 3 itens, continua subindo (a última entrega, HU-T01-4)' },
  'T02/02-estado-lista-longa-com-busca': { casos: ['lista-longa-garagens'], obs: 'a mesma empresa com 9 unidades em 3 regiões: mais de 6, a busca aparece (entrega do design de 24/09)' },
  'T02/05-estado-escolher-a-empresa': { dados: ['empresas'], obs: 'a entrada do herói: as três empresas dele (M.empresas), cada uma com a contagem das unidades, e nada escolhido — o primário espera (a otimização do design, 25/09; o mundo do herói desde a otimização 400, 26/09)' },
  'T02/06-estado-unidades-com-trocar-empresa': { dados: ['empresas', 'ucs', 'uos'], obs: 'as unidades da Viação Atlântico Sul, a empresa do herói — as do mundo dele —, com o Trocar de empresa no rodapé (a otimização do design, 25/09; o mundo do herói desde a otimização 400, 26/09)' },
  'T02/08-estado-uma-empresa-ja-marcada': { casos: ['uma-empresa'], obs: 'a entrada de quem tem uma empresa só: a lista com ela já marcada e o Ver as unidades aceso — o técnico só confirma (a otimização 400, 26/09, decisão 37 revista)' },
  'T03/01-estado-falha-de-rede': { casos: ['sync-falha-rede'] },
  'T03/03-estado-pacote-de-4-dias': { dados: ['pacotes'] },
  'T03/04-estado-pacote-vencido': { dados: ['pacotes'] },
  'T04/03-estado-faixa-modulo-com-falha': { casos: ['link-perdido'], obs: 'só "o link caiu", na sessão do herói' },
  'T04/04-estado-checklist-pendente': { dados: ['checklist'] },
  'T04/08-estado-folha-trocar-de-garagem-envio-em-andamento': { dados: ['filaSaida'] },
  'T04/09-estado-folha-trocar-de-garagem-com-modulo-conectado': { dados: ['situacao'] },
  'T04/12-estado-acesso-vencendo': { dados: ['situacao.sessaoAcesso'], obs: 'o 5º dia da sessão de acesso: o diálogo aparece na primeira chegada ao menu (entrega do design de 25/09)' },
  'T04/14-estado-folha-trocar-de-unidade-com-empresa': { dados: ['empresas', 'uos', 'pacotes'], obs: 'a folha de trocar de unidade do herói, com as três empresas dele: as unidades da Viação Atlântico Sul, e o Trocar de empresa no fim (a otimização do design, 25/09, decisão 37; o mundo do herói desde a otimização 400, 26/09)' },
  'T05/03-estado-nenhum-encontrado': { casos: ['busca-vazia'] },
  'T05/04-estado-conexao-falhou': { casos: ['conexao-falha'] },
  'T05/16-estado-bluetooth-desligado': { casos: ['bluetooth-desligado'], obs: 'Ligar o Bluetooth pede ao Android, e a busca começa sozinha (entrega do design de 25/09, o mundo real)' },
  'T05/17-estado-bluetooth-sem-permissao': { casos: ['bluetooth-sem-permissao'], obs: 'Permitir pede de novo; com não perguntar de novo, Abrir as configurações (entrega do design de 25/09, o mundo real)' },
  'T06/04-estado-fora-do-pacote': { casos: ['ativo-fora-pacote'] },
  'T06/05-estado-conflito-de-pinos-resolvivel': { casos: ['conflito-pinos-resolvivel'] },
  'T06/06-estado-conflito-de-pinos-sem-saida': { casos: ['conflito-pinos-sem-saida'] },
  'T09/01-estado-bloco-recusado': { casos: ['bloco-recusado'] },
  'T09/02-estado-queda-na-cadeia': { casos: ['queda-na-cadeia'] },
  'T09/03-estado-recuperacao-ate-a-conexao-gravar': { casos: ['queda-na-cadeia'] },
  'T10/02-estado-rotacao-caminhao-coletor': { dados: ['calibracao.porModelo'] },
  'T10/03-estado-ja-semeado': { dados: ['calibracao.ultimas'] },
  'T10/04-estado-modulo-sem-pulsos': { casos: ['grandeza-indisponivel'], dados: ['calibracao.bruto'] },
  'T10/10-estado-releitura-nao-confere': { casos: ['releitura-nao-confere'], obs: 'a releitura 500 m abaixo, e a tolerância é 120 m: não confere, e Semear de novo (entrega do design de 25/09)' },
  'T10/11-estado-camera-sem-permissao': { casos: ['camera-sem-permissao'], obs: 'a câmera sem permissão: o quadro diz o que falta, e Abrir as configurações (entrega do design de 25/09, o mundo real)' },
  'T11/01-estado-conteudo-que-o-app-nao-reconhece': { casos: ['indice-nao-classificado'], obs: 'os cinco blocos conferem, e o conteúdo fora deles é 1 a mais (entrega do checklist)' },
  'T11/04-estado-versao-ilegivel': { casos: ['versao-ilegivel'], obs: 'a versão do módulo não se lê: o diff roda por conteúdo, no par da semente, e acha as 2 que o caso diz; corrigir as Cercas arrasta o Leitor e os Eventos (a última entrega, decisão 40)' },
  'T12/02-estado-nenhuma-instalacao': { dados: ['instalacoes'], aditivo: 'instalacoes-vazia' },
  'T12/03-estado-sem-rede': { casos: ['instalacoes-sem-rede'] },
  'T12/04-estado-criterio-indisponivel': { casos: ['criterio-indisponivel'], dados: ['instalacoes'], obs: 'a PCX-9A17: o pacote não declara a fila, e os eventos ficam indisponíveis, com o motivo; o status geral espera (a última entrega, decisão 41)' },
  'T12/05-estado-criterio-pendente': { casos: ['criterio-pendente'], dados: ['instalacoes'], obs: 'a PCX-9A17: o servidor não respondeu, e o posicionamento fica pendente, confere por 24 h; o status geral espera (a última entrega, decisão 41)' },
  'T13/09-estado-item-reprovado': { casos: ['can-estatico-bateria'] },
  'T13/10-estado-finalizar-com-a-secao-f-falhando': { casos: ['pronto-para-fechar'] },
  'T13/14-estado-homologado-sem-localizacao': { casos: ['localizacao-negada'], obs: 'homologa igual, e o relatório vai sem a geolocalização (entrega do design de 25/09, o checklist numa estrutura só)' },
  'T14/02-estado-prazo-estourado': { casos: ['evento-sem-resposta'] },
  'T14/03-estado-dinamico-fora-do-esperado': { casos: ['can-fora-esperado'] },
  'T14/04-estado-identificador-divergente': { casos: ['identificador-divergente'] },
  'T15/01-estado-sem-erro': { dados: ['filaSaida'], aditivo: 'fila-sem-erro' },
  'T15/02-estado-dois-erros': { dados: ['filaSaida'], aditivo: 'fila-dois-erros' },
  'T15/03-estado-fila-vazia': { casos: ['fila-vazia'], dados: ['filaSaida'], obs: 'o caso é do design desde a última entrega (o 14:02); o protótipo só acrescenta a fila vazia e a sessão' },
  'T15/04-estado-secao-f-em-re-checagem': { casos: ['fila-vazia'], dados: ['secaoF'], obs: 'a Seção F sobre a fila vazia do 03' },
  'T16/05-estado-assertiva-falhando': { casos: ['autoteste-falhando'] },
  'T16/06-estado-sessao-interrompida': { casos: ['sessao-interrompida'] },
}
