// As receitas dos estados (G21): de que caso ou dado do mock cada estado
// nasce. `casos` são chaves de M.casos; `dados`, caminhos de M. Onde nada no
// mock produz o estado, a receita diz `aditivo` — o caso entra no ciclo da
// tela (G8). Cada ciclo de tela completa as receitas das suas telas.
export const RECEITAS = {
  'T01/01-estado-usuario-ou-senha-incorretos': { dados: ['credenciais'] },
  'T01/06-estado-codigo-expirado': { dados: ['credenciais.recuperacao.limites.validadeMin'] },
  'T01/07-estado-tentativas-esgotadas': { dados: ['credenciais.recuperacao.limites.tentativas'] },
  'T01/14-estado-login-sem-conexao': { casos: ['sem-conexao-no-login'], obs: 'o Entrar sem internet: o aviso, e os campos ficam preenchidos (entrega do design de 25/09, o mundo real)' },
  'T01/15-estado-primeiro-acesso': { casos: ['primeiro-acesso'], obs: 'nada lembrado: os dois campos vazios, o foco no usuário, e o Entrar diz Digite o usuário (a otimização do design, 25/09)' },
  'T01/16-estado-usuario-lembrado': { casos: ['usuario-lembrado'], obs: 'o r.vieira lembrado, com o xis, a caixa marcada e o foco na senha (a otimização do design, 25/09)' },
  'T01/17-estado-teto-de-envios': { casos: ['teto-de-envios'], dados: ['credenciais.recuperacao.limites.tetoPorHora'], obs: 'os 3 envios da hora acabaram: o código do mock enviado segue valendo, e a linha diz até quando, pela hora do caso (a última entrega, HU-T01-7)' },
  'T01/18-estado-outro-usuario-no-aparelho': { casos: ['outro-usuario'], dados: ['ucs', 'uos', 'pacotes'], obs: 'as unidades da T02 com o diálogo Outra sessão neste aparelho: a sessão do r.vieira encerrada, e a fila dele, 3 itens, continua subindo (a última entrega, HU-T01-4)' },
  'T02/02-estado-lista-longa-com-busca': { casos: ['lista-longa-garagens'], obs: 'a mesma empresa com 9 unidades em 3 regiões: mais de 6, a busca aparece (entrega do design de 24/09)' },
  'T02/05-estado-escolher-a-empresa': { dados: ['empresas'], obs: 'a entrada do herói: as três empresas dele (M.empresas), cada uma com a contagem das unidades, e nada escolhido — o primário espera (a otimização do design, 25/09; o mundo do herói desde a otimização 400, 26/09)' },
  'T02/06-estado-unidades-com-trocar-empresa': { dados: ['empresas', 'ucs', 'uos'], obs: 'as unidades da Viação Atlântico Sul, a empresa do herói — as do mundo dele —, com o Trocar de empresa no rodapé (a otimização do design, 25/09; o mundo do herói desde a otimização 400, 26/09)' },
  'T02/08-estado-uma-empresa-ja-marcada': { casos: ['uma-empresa'], obs: 'a entrada de quem tem uma empresa só: a lista com ela já marcada e o Ver as unidades aceso — o técnico só confirma (a otimização 400, 26/09, decisão 37 revista)' },
  'T03/01-estado-falha-de-rede': { casos: ['sync-falha-rede'] },
  'T03/03-estado-pacote-de-4-dias': { dados: ['pacotes'] },
  'T03/04-estado-pacote-vencido': { dados: ['pacotes'] },
  'T04/03-estado-faixa-modulo-com-falha': { casos: ['link-perdido'], obs: 'só "o link caiu", na sessão do herói' },
  'T04/04-estado-checklist-pendente': { dados: ['checklist'] },
  'T04/08-estado-folha-trocar-de-garagem-envio-em-andamento': { dados: ['filaSaida'] },
  'T04/09-estado-folha-trocar-de-garagem-com-modulo-conectado': { dados: ['situacao'] },
  'T04/12-estado-acesso-vencendo': { dados: ['situacao.sessaoAcesso'], obs: 'o 5º dia da sessão de acesso: o diálogo aparece na primeira chegada ao menu (entrega do design de 25/09)' },
  'T04/14-estado-folha-trocar-de-unidade-com-empresa': { dados: ['empresas', 'uos', 'pacotes'], obs: 'a folha de trocar de unidade do herói, com as três empresas dele: as unidades da Viação Atlântico Sul, e o Trocar de empresa no fim (a otimização do design, 25/09, decisão 37; o mundo do herói desde a otimização 400, 26/09)' },
  'T04/15-estado-sem-conexao': { casos: ['sem-conexao-no-menu'], obs: 'o aparelho sem rede, na sessão do herói: só o Últimas instalações espera a conexão, e o resto do menu fica de pé (pacote 1, decisão 48)' },
  'T04/16-estado-fila-parada': { casos: ['fila-parada'], obs: 'a fila parada há 32 min, na sessão do herói: o diálogo sobre o menu, no molde do acesso vencendo · padrão até o PM decidir (o pacote 12)' },
  'T05/03-estado-nenhum-encontrado': { casos: ['busca-vazia'] },
  'T05/04-estado-conexao-falhou': { casos: ['conexao-falha'] },
  'T05/16-estado-bluetooth-desligado': { casos: ['bluetooth-desligado'], obs: 'Ligar o Bluetooth pede ao Android, e a busca começa sozinha (entrega do design de 25/09, o mundo real)' },
  'T05/18-estado-pareando': { casos: ['pareando'], obs: 'a primeira conexão com um VL06: confirme no celular · só pela coluna (a rodada 2 do retorno do PM)' },
  'T05/19-estado-reconectando': { casos: ['reconectando'], obs: 'a conexão que caiu parada: o app reconecta sozinho, nunca falha · só pela coluna (a rodada 2)' },
  'T05/17-estado-bluetooth-sem-permissao': { casos: ['bluetooth-sem-permissao'], obs: 'Permitir pede de novo; com não perguntar de novo, Abrir as configurações (entrega do design de 25/09, o mundo real)' },
  'T06/04-estado-fora-do-pacote': { casos: ['ativo-fora-pacote'] },
  'T06/06-estado-conflito-de-pinos-sem-saida': { casos: ['conflito-pinos-sem-saida'] },
  'T06/10-estado-modulo-em-outro-ativo': { casos: ['modulo-em-outro-ativo'], obs: 'o M2C-0417 da faixa está no QTM-5S79 (a-18): o aviso, e Desvincular e vincular aqui registra o desvínculo e segue pra T09 · o ônibus é o do módulo no pacote, o RKT-8H42 (o caso não traz ativo) · só pela coluna (D1)' },
  'T06/11-estado-modulo-ja-deste-ativo': { casos: ['modulo-ja-deste-ativo'], obs: 'o M2C-0417 já é do RKT-8H42: é manutenção, e Seguir pra manutenção grava o modo do caso e segue pra T09 · só pela coluna (D1)' },
  'T07/02-estado-serial-nao-cadastrado': { casos: ['serial-nao-cadastrado'], obs: 'o M2C-0999 fora do cadastro: o serial trava, o firmware e as entradas ficam sem cadastro, e a faixa não desce · no fluxo, conectar no M2C-0999 da T05/01 (a errata)' },
  'T07/03-estado-modelo-sem-suporte': { casos: ['modelo-sem-driver'], obs: 'o M2C-0497, VC07 sem driver nesta versão: o serial trava · o módulo não está por perto, só pela coluna' },
  'T07/04-estado-firmware-fora-da-lista': { casos: ['firmware-fora-matriz'], obs: 'o M2C-0451 com o 2.4.1, fora da lista do VL06 FULL: o firmware trava, e Atualizar firmware leva à 06 · só pela coluna' },
  'T07/13-estado-sessao-anterior-mal-encerrada': { casos: ['modulo-com-pendencias'], obs: 'o M2C-0362 com o canal aberto: o app fecha o acesso e avisa, e as 12 mensagens guardadas aparecem na linha delas (a rodada 2) · no fluxo, conectar no M2C-0362' },
  'T07/05-estado-firmware-sem-rede-no-modulo': { casos: ['firmware-sem-rede-no-modulo'], obs: 'o firmware-fora-matriz com o modem sem rede, que só informa: Gravar a conexão grava só a conexão, e o firmware atualiza (a 06) · só pela coluna' },
  'T07/07-estado-modem-sem-sinal': { casos: ['modem-sem-sinal'], obs: 'o M2C-0417 com o modem sem sinal, que só informa: a faixa desce, 6 de 7 · só pela coluna (D1)' },
  'T07/08-estado-sinal-da-can-sem-leitura': { casos: ['can-estatico-ausente'], obs: 'a CAN lida do RKT-8H42 (a-01), com a rotação sem leitura, a ligação: 14 de 15 · só pela coluna (D1)' },
  'T07/09-estado-sinal-da-can-fora-do-esperado': { casos: ['can-estatico-isolado'], obs: 'a CAN lida do RKT-8H42 (a-01), com a temperatura em 215 °C, fora de −40 a 120: 14 de 15 · só pela coluna (D1)' },
  'T07/12-estado-alimentacao-abaixo-da-faixa': { casos: ['can-estatico-bateria'], obs: 'o M2C-0301 com a alimentação em 10,9 V, abaixo da faixa, que só informa: 6 de 7, e o Selecionar ativo aceso · só pela coluna (o pacote 10)' },
  'T09/01-estado-bloco-recusado': { casos: ['bloco-recusado'] },
  'T09/02-estado-queda-na-cadeia': { casos: ['queda-na-cadeia'] },
  'T09/03-estado-recuperacao-ate-a-conexao-gravar': { casos: ['queda-na-cadeia'] },
  'T09/06-estado-a-configuracao-nao-cabe': { casos: ['conteudo-nao-cabe'], dados: ['modelosAtivo', 'matrizCapacidades', 'cercas'], obs: 'o OCT-2J85 com o M2C-0394: São 131 contadores. Este módulo guarda 127. — o que estourou, nomeado (a rodada 1 do retorno do PM)' },
  'T09/07-estado-pontos-de-cerca-demais': { casos: ['pool-esgotado'], dados: ['matrizCapacidades'], obs: 'o OYS-7D93 com o M2C-0348 do cadastro: As cercas têm 6.410 pontos. Este módulo guarda 6.143. (a rodada 1 do retorno do PM)' },
  'T09/12-estado-o-modulo-ainda-nao-falou-com-o-servidor': { casos: ['servidor-ainda-nao'], obs: 'a Conexão gravada e conferida, e o módulo ainda não falou com o servidor: o que conferir, chip, antena e endereço (a rodada 1 do retorno do PM)' },
  'T10/02-estado-rotacao-caminhao-coletor': { dados: ['calibracao.porModelo'] },
  'T10/03-estado-ja-semeado': { dados: ['calibracao.ultimas'] },
  'T10/04-estado-modulo-sem-pulsos': { casos: ['grandeza-indisponivel'], dados: ['calibracao.bruto'] },
  'T10/11-estado-nada-a-calibrar': { dados: ['calibracao.porModelo'], obs: 'o ônibus lê rotação e hodômetro da CAN: nada a calibrar, e o ciclo de testes direto (a rodada 2 do retorno do PM) · no fluxo, o herói chega aqui' },
  'T10/10-estado-releitura-nao-confere': { casos: ['releitura-nao-confere'], obs: 'a releitura 500 m abaixo, e a tolerância é 120 m: não confere, e Semear de novo (entrega do design de 25/09)' },
  'T11/00-tela': { casos: ['diff-divergente'], obs: 'consulta parada do par divergente; independe da cadeia do fluxo guardado' },
  'T11/03-momento-outras-acoes': { casos: ['diff-divergente'], obs: 'a folha do exemplo divergente, parada sobre a conferência' },
  'T11/01-estado-conteudo-que-o-app-nao-reconhece': { casos: ['indice-nao-classificado'], obs: 'as quatro que se comparam conferem, o Extended ID só informa, e o conteúdo fora dos blocos é 1 a mais (entrega do checklist; o pacote 2)' },
  'T11/05-estado-revisar-em-seguida': { casos: ['cercas-reenviadas'], obs: 'o herói (RKT-8H42 + M2C-0417) depois de reenviar as cercas numa manutenção: elas conferem, e o leitor e os eventos ficam revisar em seguida, pelo arraste — Revisar o leitor (o pacote 2, decisão 53)' },
  'T12/02-estado-nenhuma-instalacao': { dados: ['instalacoes'], aditivo: 'instalacoes-vazia' },
  'T12/03-estado-sem-rede': { casos: ['instalacoes-sem-rede'] },
  'T12/04-estado-criterio-indisponivel': { casos: ['criterio-indisponivel'], dados: ['instalacoes'], obs: 'a PCX-9A17: o pacote não declara a fila, e os eventos ficam indisponíveis, com o motivo; o status geral espera (a última entrega, decisão 41)' },
  'T12/05-estado-criterio-pendente': { casos: ['criterio-pendente'], dados: ['instalacoes'], obs: 'a PCX-9A17: o servidor não respondeu, e o posicionamento fica pendente, confere por 24 h; o status geral espera (a última entrega, decisão 41)' },
  'T13/09-estado-item-reprovado': { casos: ['can-estatico-bateria'] },
  'T13/10-estado-finalizar-com-a-secao-f-falhando': { casos: ['pronto-para-fechar'] },
  'T13/14-estado-aguardando-autoteste-sem-localizacao': { casos: ['localizacao-negada'], obs: 'o checklist registrado, aguardando autoteste, e o relatório vai sem a localização (a rodada 1 do retorno do PM: a homologação é da T16)' },
  'T13/16-estado-secao-c-com-item-reprovado': { casos: ['can-estatico-bateria'], obs: 'o QJF-2C61 com o M2C-0301: a Alimentação reprovada em 10,9 V, com a seta pro 09 · a Seção C aberta, 16 de 31 (o pacote 10)' },
  'T13/21-estado-secao-c-com-gps-reprovado': { casos: ['gps-fraco'], obs: 'o herói com 4 satélites, o mínimo 6 do caso: a linha vermelha e a seta pro 22 (o pacote 12)' },
  'T13/22-estado-gps-reprovado': { casos: ['gps-fraco'], obs: 'o detalhe do GPS: a régua dos satélites e o que conferir (o pacote 12)' },
  'T13/23-estado-secao-c-com-entradas-reprovadas': { casos: ['entrada-ignicao'], obs: 'o herói com a ignição desligada: a linha vermelha e a seta pro 24 (o pacote 12)' },
  'T13/24-estado-entradas-reprovadas': { casos: ['entrada-ignicao'], obs: 'o detalhe das entradas: o lido e o esperado, sem régua (o pacote 12)' },
  'T13/25-estado-secao-c-com-modem-reprovado': { casos: ['modem-sem-sinal'], obs: 'o herói com o modem sem sinal, o caso da T07/07: a linha vermelha e a seta pro 26 (o pacote 12)' },
  'T13/26-estado-modem-reprovado': { casos: ['modem-sem-sinal'], obs: 'o detalhe do modem: sem sinal e o porquê, sem régua (o pacote 12)' },
  'T14/02-estado-prazo-estourado': { casos: ['evento-sem-resposta'] },
  'T14/03-estado-dinamico-fora-do-esperado': { casos: ['motor-desligado-no-ciclo'] },
  'T14/12-estado-ativo-sem-leitor': { casos: ['sem-leitor'], obs: 'o herói sem o leitor: o ciclo em 3 passos, sem o cartão, concluído (a rodada 1 do retorno do PM)' },
  'T14/09-estado-segunda-falha-do-evento': { casos: ['evento-nao-chega-de-novo'], obs: 'o KHT-4B08 com o evento que não chega nas duas tentativas: a 2ª estoura, com o confira a conexão do módulo (o pacote 12)' },
  'T15/01-estado-sem-erro': { dados: ['filaSaida'], aditivo: 'fila-sem-erro' },
  'T15/02-estado-dois-erros': { dados: ['filaSaida'], aditivo: 'fila-dois-erros' },
  'T15/03-estado-fila-vazia': { casos: ['fila-vazia'], dados: ['filaSaida'], obs: 'o caso é do design desde a última entrega (o 14:02); o protótipo só acrescenta a fila vazia e a sessão' },
  'T15/04-estado-secao-f-em-re-checagem': { casos: ['fila-vazia'], dados: ['secaoF'], obs: 'a Seção F sobre a fila vazia do 03' },
  'T16/05-estado-homologacao-bloqueada': { casos: ['autoteste-falhando'], obs: 'os contadores voltam zerados no reinício: a homologação fica bloqueada, com a causa (a rodada 1 do retorno do PM)' },
  'T16/06-estado-sessao-interrompida': { casos: ['sessao-interrompida'] },
}
