// C11 · ENCERRAR antes de homologar (logica.md, ENCERRAR): os 4 passos sem confirmação,
// a Sessão encerrada sem homologar, e o menu sem sessão. Só por toque, do login.
const ATE_A_FAIXA = [
  { toca: 'CONECTAR MÓDULO' },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  { marca: 'M2C-0417' },
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  { ve: 'ENCERRAR', ms: 12000 },
  { ve: '11 de 11' },
]
// os 4 passos, um a cada 600 ms (encerramentoPassoMs), sem diálogo nenhum no caminho
const OS_QUATRO_PASSOS = [
  { chega: 'T16', momento: '03-momento-encerrando-sem-homologar', ms: 1000 },
  // o primeiro dos quatro corre dizendo o que faz (as legendas do tela.md, a entrega de 25/09)
  { ve: 'Devolve o módulo ao repouso que ele tinha antes da sessão.', ms: 500 },
  { naoVe: 'Cancelar', ms: 300 },
  { ve: 'Sem homologar · só o que deixa o módulo seguro' },
  { ve: 'Encerrando · não desconecte' },
  { ve: 'A saída volta quando o módulo desconectar' },
  { ve: 'pulado' },
  // o segundo dos quatro, com a legenda dele
  { ve: 'Fecha o canal que o app abriu no módulo. Ele fecha sempre, mesmo sem homologar.', entre: [0, 1000] },
  { fica: 'T16', ms: 300 },
  { tecla: 'Escape' },   // no encerramento, o voltar não faz nada
  // o terceiro e o quarto, cada um com a sua, um a cada 600 ms
  { ve: 'Guarda o que foi feito aqui, pra ir ao servidor junto com a instalação.', entre: [0, 1000] },
  { ve: 'Solta o Bluetooth. O módulo fica livre pra outro aparelho.', entre: [300, 1000] },
  { chega: 'T16', momento: '04-momento-encerrada-sem-homologar', entre: [300, 1000] },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { ve: 'SEM HOMOLOGAR' },
  { ve: 'A instalação continua aberta. O que foi gravado fica no módulo.' },
  { ve: 'restaurado' },
  { ve: 'fechado' },
  { ve: 'na fila' },
  { ve: 'feita' },
  { ve: 'NÃO RODARAM' },
  { ve: 'Contadores, reinício, releitura e o autoteste.' },
  { toca: 'Voltar ao menu' },
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { ve: 'toque para procurar' },
]

export default [
  { abre: '' },
  { chega: 'T01', momento: null },
  { digita: 'Varzea26', em: 'SENHA' },
  { toca: 'Entrar' },
  { chega: 'T02' },
  { marca: 'Garagem Várzea' },
  { toca: 'Sincronizar Garagem Várzea' },
  { chega: 'T03', momento: '02-momento-concluido', ms: 8000 },
  { toca: 'Ir para o menu' },
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  // o 5º dia do acesso: o aviso na primeira chegada ao menu, e o Entendi fecha (T04/12)
  { ve: 'Seu acesso vence em 2 dias' },
  { toca: 'Entendi' },
  { naoVe: 'Seu acesso vence em 2 dias' },
  // 1ª passada: com o ônibus na sessão, ENCERRAR da faixa na CAN
  ...ATE_A_FAIXA,
  { toca: 'Selecionar ativo' },
  { chega: 'T06' },
  { marca: 'RKT-8H42' },
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { toca: 'Usar este ativo' },
  { chega: 'T07' },
  { ve: 'RKT-8H42' },
  { toca: 'ENCERRAR' },
  ...OS_QUATRO_PASSOS,
  // 2ª passada: a sessão recém-nascida, sem ativo, ENCERRAR na própria pré-checagem
  ...ATE_A_FAIXA,
  { ve: 'sem ativo' },
  { toca: 'ENCERRAR' },
  ...OS_QUATRO_PASSOS,
  // 3ª passada: do menu, com a sessão aberta
  ...ATE_A_FAIXA,
  { toca: 'Voltar ao menu' },
  { chega: 'T04', momento: '02-momento-modulo-sem-ativo' },
  { ve: 'sem ativo' },
  { toca: 'ENCERRAR' },
  ...OS_QUATRO_PASSOS,
  // 4ª passada: a folha do módulo travado na sessão, cujo Encerrar a sessão é o ENCERRAR da faixa
  ...ATE_A_FAIXA,
  { toca: 'Voltar ao menu' },
  { chega: 'T04', momento: '02-momento-modulo-sem-ativo' },
  { toca: 'CONECTAR MÓDULO, M2C-0417' },
  { chega: 'T04', momento: '10-momento-folha-modulo-conectado' },
  { ve: 'Módulo conectado' },
  { ve: 'VL06 · CAN-BT · firmware 2.3.5' },
  { ve: 'TRAVADO NA SESSÃO' },
  { ve: 'Enquanto a sessão estiver aberta, o módulo não troca. Pra trocar de módulo, encerre a sessão.' },
  { toca: 'Encerrar a sessão' },
  ...OS_QUATRO_PASSOS,
]
