// A conferência normal e sua folha continuam interativas. Divergências e manutenção são consultas.
const CONFERE = '02-momento-tudo-confere'
const fecha = [{ prop: 'transform', ms: 150, em: 'ds-folha' }, { prop: 'opacity', ms: 150, em: 'ds-veu' }]
const folha = [
  { toca: 'Outras ações' },
  { chega: 'T11', momento: CONFERE },
  { ve: 'Mantém a rede do módulo. Apaga só a configuração.' },
  { ve: 'nada vai pro módulo · só o diagnóstico sobe' },
]
export default [
  { abre: '?tela=T11' },
  { ve: 'CONFERE COM O CADASTRO', ms: 5000 },
  { ve: '4 de 4' },
  { naoVe: 'Corrigir este bloco' },
  ...folha,
  // 08/10 · a faixa fica inerte atrás do véu de Outras ações, fora do toque e do leitor
  { naoToca: 'ENCERRAR' },
  { toca: 'Fechar' },
  { naoVe: 'Reenviar os 5 blocos' },
  { toca: 'ENCERRAR' },
  { ve: 'Encerrar antes de terminar?' },
  { toca: 'Continuar a instalação' },
  ...folha,
  { tocaFora: 'Outras ações', anima: fecha },
  { naoVe: 'Reenviar os 5 blocos' },
  ...folha,
  { arrasta: 'Outras ações', dy: 40, anima: [{ prop: 'transform', ms: 200, em: 'ds-folha' }] },
  { ve: 'Reenviar os 5 blocos' },
  { arrasta: 'Outras ações', dy: 120, anima: fecha },
  { naoVe: 'Reenviar os 5 blocos' },
  ...folha,
  { tecla: 'Escape' },
  { naoVe: 'Reenviar os 5 blocos' },
  ...folha,
  { toca: 'Apenas registrar o diagnóstico' },
  { chega: 'T04' },
  // O reenvio segue a cadeia normal, inclusive quando a cadeia anterior já concluiu.
  { abre: '?tela=T11' },
  { ve: 'CONFERE COM O CADASTRO', ms: 5000 },
  ...folha,
  { toca: 'Reenviar os 5 blocos' },
  { chega: 'T09', momento: '05-momento-o-que-vai-ser-gravado' },
  { toca: 'Gravar no módulo' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', ms: 15000 },
  { toca: 'Voltar ao menu' },
  { toca: 'Entendi' },
  { toca: 'Conferir configuração' },
  { ve: 'CONFERE COM O CADASTRO', ms: 5000 },
  ...folha,
  { toca: 'Reenviar os 5 blocos' },
  { chega: 'T09', momento: '05-momento-o-que-vai-ser-gravado' },
  { toca: 'Gravar no módulo' },
  { chega: 'T09', momento: null },
  { desligado: 'Gravando · não interrompa' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', ms: 15000 },
  // Exemplos especiais ficam no mesmo quadro, sem transformar a consulta em percurso.
  ...[
    ['00-tela', 'NÃO BATE COM O CADASTRO'],
    ['03-momento-outras-acoes', 'Reenviar os 5 blocos'],
    ['01-estado-conteudo-que-o-app-nao-reconhece', '1 a mais'],
    ['05-estado-revisar-em-seguida', 'REVISAR EM SEGUIDA'],
  ].flatMap(([estado, texto]) => [
    { abre: `?tela=T11&estado=${estado}` },
    { chega: 'T11', estado },
    { ve: texto },
    { quieto: true },
    { naoToca: 'Corrigir este bloco' },
    { naoToca: 'Reenviar os 5 blocos' },
    { tecla: 'Escape' },
    { fica: 'T11', ms: 1800 },
    { chega: 'T11', estado },
  ]),
]
