// C11 · o caminho do herói inteiro (logica.md, "O caminho do herói"), só por toque:
// do login às 14:30 ao encerramento, e de volta ao menu sem sessão.
export default [
  { abre: '' },
  { chega: 'T01', momento: null },
  { ve: '14:30' },
  { digita: 'Varzea26', em: 'SENHA' },
  { toca: 'Entrar' },
  { chega: 'T02' },
  { ve: 'Onde você está hoje?' },
  { marca: 'Garagem Várzea' },
  { fica: 'T02', ms: 600 },
  { toca: 'Sincronizar Garagem Várzea' },
  { chega: 'T03' },
  { chega: 'T03', momento: '02-momento-concluido', entre: [3000, 6000] },
  { ve: 'Pacote de hoje' },
  { toca: 'Ir para o menu' },
  { chega: 'T04' },
  { ve: 'Sem sessão de configuração' },
  // o herói está no 5º dia do acesso: o aviso na primeira chegada ao menu, uma vez (T04/12)
  { ve: 'Seu acesso vence em 2 dias' },
  { dorme: 200 },
  { quieto: true },   // nasce aberto, com o menu: a chegada não anima
  { ve: 'Depois disso, ele pede a senha de novo — e pra isso precisa de rede.' },
  { naoToca: 'CONECTAR MÓDULO' },   // o menu atrás do véu não se toca
  { toca: 'Entendi', anima: [{ prop: 'opacity', ms: 150, em: 'ds-dialogo' }, { prop: 'opacity', ms: 150, em: 'ds-veu' }] },
  { naoVe: 'Seu acesso vence em 2 dias' },
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  // conectar: a lista, marcar o do herói e o botão (R-14)
  { toca: 'CONECTAR MÓDULO' },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  { ve: 'Escolha o que está na sua mão.' },
  { marca: 'M2C-0417' },
  { fica: 'T05', ms: 600 },
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  // a pré-checagem acende as onze linhas, uma a cada 600 ms; aprovada, a sessão nasce e a faixa desce
  { naoVe: 'ENCERRAR', ms: 300 },
  { ve: 'Rede do módulo' },
  { ve: 'ENCERRAR', entre: [4000, 9000] },
  { ve: 'M2C-0417' },   // o serial na faixa: o rótulo do topo sai quando ela desce
  { ve: 'sem ativo' },
  { ve: '11 de 11' },
  { ve: 'Serial no cadastro' },
  { ve: 'VL06 CAN-BT' },
  { ve: '128 de 192' },
  { ve: 'nenhuma' },
  { ve: 'conectada' },
  { toca: 'Selecionar ativo' },
  { chega: 'T06' },
  { ve: 'M2C-0417' },
  // o ônibus: marcar o RKT-8H42 e o botão (R-14); a confirmação: os chassis batem
  { marca: 'RKT-8H42' },
  { fica: 'T06', ms: 600 },
  { naoVe: 'Confirmar o veículo', ms: 300 },
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'CHASSI LIDO DO VEÍCULO' },
  { ve: '9BM384067GB120401' },
  { ve: 'Os dois batem — é este veículo.' },
  { toca: 'Usar este ativo' },
  // a CAN lida
  { chega: 'T07' },
  { ve: 'RKT-8H42' },
  { ve: 'TENSÃO DA BATERIA' },
  { ve: 'de 12' },
  { toca: 'Configurar módulo' },
  // a cadeia grava e relê os blocos, um por segundo: Leitor → Eventos → Conexão
  { chega: 'T09' },
  { ve: 'Gravando · não interrompa' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', entre: [2000, 5000] },
  { ve: 'GRAVADO E RELIDO' },
  { ve: 'A12.G07.L02.E05.C03' },
  { ve: 'o módulo devolveu os seis blocos' },
  { toca: 'Voltar ao menu' },
  { chega: 'T04' },
  // a calibração só semeia com a prova (decisão 33): o número do painel digitado e a foto
  // da câmera do app; o botão diz o que falta. O hodômetro, e depois o horímetro, até a
  // calibração completa, que aponta o ciclo dinâmico (decisão 35)
  { toca: 'Calibração' },
  { chega: 'T10', momento: null },
  { ve: 'O MÓDULO CONTA' },
  { ve: '184.320' },
  { ve: 'lido do módulo às 14:30' },   // o relógio parado, como as referências (a entrega do checklist)
  { desligado: 'Digite o que o painel mostra' },
  { digita: '482317', em: 'O PAINEL MOSTRA' },   // calibracao.painel · a-01 · hodômetro
  { chega: 'T10', momento: '05-momento-hodometro-digitado' },
  { ve: 'diferença de 297.997 km' },
  { ve: 'é este que vai para o módulo' },
  { desligado: 'Fotografe o painel' },
  { toca: 'Fotografar o painel' },
  { chega: 'T10', momento: '06-momento-camera-do-painel' },
  { ve: 'Enquadre o hodômetro do painel' },
  { toca: 'Tirar foto' },
  { chega: 'T10', momento: '07-momento-painel-fotografado' },
  { ve: 'Painel fotografado às 14:30' },
  { ve: 'vale também no checklist, na Seção B' },
  { naoToca: 'Painel fotografado' },   // foto tirada fica tirada: o registro não se toca
  { toca: 'Semear o hodômetro' },
  { desligado: 'Gravando no módulo…' },
  { desligado: 'Voltar ao menu' },   // o semear não para (a decisão do diretor de 25/09)
  { desligado: 'ENCERRAR' },   // e o ENCERRAR faz o mesmo que o voltar: apagado (a lei 17)
  { desligado: 'Relendo…', entre: [500, 1500] },
  { chega: 'T10', momento: '01-momento-hodometro-semeado', entre: [700, 1500] },
  { ve: 'O MÓDULO CONTA AGORA' },
  { ve: 'relido às 14:30 · confere com o painel' },
  { ve: 'o mesmo que o módulo agora conta' },
  { toca: 'Calibrar o horímetro' },
  { chega: 'T10', momento: '08-momento-horimetro' },
  { ve: 'Último passo' },
  { ve: '8.540' },
  { desligado: 'Digite o que o painel mostra' },
  { digita: '9640', em: 'O PAINEL MOSTRA' },   // calibracao.painel · a-01 · horímetro
  { chega: 'T10', momento: null },   // o digitado, a câmera e o fotografado do horímetro não têm referência
  { ve: 'diferença de 1.100 h' },
  { desligado: 'Fotografe o painel' },
  { toca: 'Fotografar o painel' },
  { ve: 'Enquadre o horímetro do painel' },
  { toca: 'Tirar foto' },
  { toca: 'Semear o horímetro' },
  { desligado: 'Gravando no módulo…' },
  { chega: 'T10', momento: '09-momento-calibracao-completa', entre: [1400, 3000] },
  { ve: 'Calibração completa' },
  { ve: '9.640' },
  // a calibração aponta o ciclo (decisão 35): o caminho anda em linha — calibra, ciclo, checklist
  { ve: 'Voltar ao menu' },
  { toca: 'Fazer o ciclo dinâmico' },
  // o ciclo dinâmico: a fila do módulo drena em 3 s, e o disparo acende
  { chega: 'T14' },
  { ve: 'FILA DRENANDO' },
  { ve: '6 mensagens e 2 de diagnóstico saindo do módulo' },
  { ve: 'de 5 passos' },
  { ve: '2 de 5 passos' },   // a semente traz 2 feitos (cicloPassosNaEntrada)
  { toca: 'Disparar evento de teste', entre: [2000, 4500] },
  // disparado (1 s real vale 4 s de prazo): o evento chega aos 24 s do prazo (6 s reais) e os
  // campos conferem aos 33 (8,25 s); os passos 3 a 5 acendem a +9, +12 e +15 s (T14·1)
  { ve: 'O EVENTO CHEGOU EM', entre: [5000, 7500] },
  { ve: '0:24' },
  { ve: '6 de 6', entre: [1000, 3500] },
  { ve: '3 de 5 passos', entre: [0, 1800] },
  { ve: '4 de 5 passos', entre: [2400, 3600] },
  { chega: 'T14', momento: '05-momento-ciclo-concluido', entre: [2400, 3600] },
  { ve: '5 de 5 passos' },
  { ve: '14:30:24' },
  // o checklist numa estrutura só (decisão 34): o título com a contagem, a barra e os seis cartões.
  // Depois do ciclo, 24 de 31: a E resolvida, e as quatro fotos de B por fazer (o Painel vem da calibração)
  { toca: 'Voltar ao checklist' },
  { chega: 'T13', momento: null },
  { ve: 'de 31' },
  { ve: 'o ciclo passou' },
  { ve: 'você fotografa 4 itens' },
  { ve: 'Faltam 4 itens' },
  { desligado: 'Finalizar instalação' },
  // a E aberta: os cinco passos dizem confere, e não há ação (13); tocar de novo fecha
  { toca: 'E · Teste dinâmico' },
  { chega: 'T13', momento: '13-momento-e-resolvida' },
  { ve: 'confere' },
  { naoToca: 'Fazer o ciclo dinâmico' },
  { naoToca: 'Ignição ligada' },   // sem seta, é leitura (Lei 16)
  { toca: 'E · Teste dinâmico' },
  { chega: 'T13', momento: null },
  // a B cresce no lugar: os itens esmaecem, e as seções de baixo descem (transform)
  { toca: 'B · Montagem', anima: [{ prop: 'opacity', ms: 200, em: 'ds-secao-ck-corpo' }, { prop: 'transform', ms: 200, em: 'ds-secao-ck' }] },
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  { ve: 'fotografado na calibração, às 14:30' },
  { naoToca: 'Painel' },   // o Painel herdado não se fotografa de novo
  { toca: 'Módulo' },
  { chega: 'T13', momento: '07-momento-responder-item' },
  { ve: 'B · INSTALAÇÃO FÍSICA' },
  { ve: 'Módulo fixado e posicionado' },
  { ve: 'Depois: Antena GPS posicionada e livre' },
  { toca: 'Tirar foto' },
  { ve: 'Antena GPS posicionada e livre' },
  { toca: 'Tirar foto' },
  { ve: 'Chicote e emendas protegidos' },
  { toca: 'Tirar foto' },
  { ve: 'Leitor posicionado' },
  { toca: 'Tirar foto' },
  // sem próximo por fazer, volta à Seção B aberta: 5 de 5, e as fotos tiradas
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  { ve: 'B · Montagem' },
  { ve: '5 de 5' },
  { ve: '5 fotos tiradas' },
  { naoToca: 'Módulo' },   // a foto tirada fica tirada: sem seta, não se toca
  { naoVe: 'Faltam' },
  { toca: 'Finalizar instalação' },
  // o homologado: o veredito e o relatório no topo, e o servidor confirmou
  { chega: 'T13', momento: '11-momento-homologado' },
  { ve: 'Instalação homologada às 14:30' },
  { ve: 'o relatório leva 12 evidências, o local e o seu nome' },
  { ve: 'o app conferiu' },
  { ve: 'o servidor confirmou' },
  { ve: 'RKT-8H42' },
  // ENCERRAR, depois de homologar: os sete passos, um a cada 600 ms, e o autoteste
  { toca: 'ENCERRAR' },
  { chega: 'T16' },
  { ve: 'Encerrar sessão' },
  { ve: 'Encerrando · não desconecte' },
  { ve: 'Contadores e estado' },
  { ve: 'Autoteste' },
  // cada passo que corre diz o que faz, embaixo do nome (as 8 legendas do tela.md, a entrega de 25/09)
  { ve: 'Grava os contadores e o estado no módulo, pra nada se perder no reinício.' },
  // o herói reinicia por comando: o passo 2 corre sem pedir o corte (T16·1, T16·7)
  { naoVe: 'Grava os contadores e o estado no módulo', entre: [0, 1000] },
  { naoVe: 'Desligue e ligue a alimentação do módulo.' },
  { ve: 'Ele lê de volta o que ficou gravado. É isto que prova que a configuração sobreviveu ao reinício.' },
  { ve: 'Devolve o módulo ao repouso que ele tinha antes da sessão.' },
  { ve: 'Fecha o canal que o app abriu no módulo. Ele fecha sempre, mesmo sem homologar.' },
  { ve: 'Guarda o que foi feito aqui, pra ir ao servidor junto com a instalação.' },
  { ve: 'Solta o Bluetooth. O módulo fica livre pra outro aparelho.' },
  // fechado o sétimo passo, a faixa sobe e a tela passa pra Sessão encerrada
  { chega: 'T16', momento: '02-momento-sessao-encerrada', entre: [100, 1500] },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { ve: 'Sessão encerrada' },
  // as oito assertivas acendem a 400 ms; a prova e o Voltar ao menu entram com a última
  { ve: 'A CONFIGURAÇÃO SOBREVIVEU AO REINÍCIO' },
  { ve: 'A12.G07.L02.E05.C03' },
  { ve: 'relido do módulo depois de desligar e ligar' },
  { ve: 'O ID na plataforma confirma quando a evidência subir.' },
  { toca: 'Voltar ao menu', entre: [2000, 5000] },
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { naoVe: 'RKT-8H42' },
  { ve: 'toque para procurar' },
  { naoVe: 'Seu acesso vence em 2 dias' },   // o aviso já foi visto: não volta no mesmo dia
  { fica: 'T04', ms: 600 },
]
