// C11 · o caminho do herói inteiro (logica.md, "O caminho do herói"), só por toque:
// do login às 14:30 ao encerramento, e de volta ao menu sem sessão.
export default [
  { abre: '' },
  { chega: 'T01', momento: null },
  { ve: '14:30' },
  { digita: 'Varzea26', em: 'SENHA' },
  { toca: 'Entrar' },
  { chega: 'T02' },
  { ve: 'Onde você está hoje?' },
  { marca: 'Garagem Várzea' },
  { fica: 'T02', ms: 600 },
  { toca: 'Sincronizar Garagem Várzea' },
  { chega: 'T03' },
  { chega: 'T03', momento: '02-momento-concluido', entre: [3000, 6000] },
  { ve: 'Pacote de hoje' },
  { toca: 'Ir para o menu' },
  { chega: 'T04' },
  { ve: 'Sem sessão de configuração' },
  // conectar: a lista, marcar o do herói e o botão (R-14)
  { toca: 'CONECTAR MÓDULO' },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  { ve: 'Escolha o que está na sua mão.' },
  { marca: 'M2C-0417' },
  { fica: 'T05', ms: 600 },
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  // a pré-checagem acende as onze linhas, uma a cada 600 ms; aprovada, a sessão nasce e a faixa desce
  { naoVe: 'ENCERRAR', ms: 300 },
  { ve: 'Rede do módulo' },
  { ve: 'ENCERRAR', entre: [4000, 9000] },
  { ve: 'M2C-0417' },   // o serial na faixa: o rótulo do topo sai quando ela desce
  { ve: 'sem ativo' },
  { ve: '11 de 11' },
  { ve: 'Serial no cadastro' },
  { ve: 'VL06 CAN-BT' },
  { ve: '128 de 192' },
  { ve: 'nenhuma' },
  { ve: 'conectada' },
  { toca: 'Selecionar ativo' },
  { chega: 'T06' },
  { ve: 'M2C-0417' },
  // o ônibus: marcar o RKT-8H42 e o botão (R-14); a confirmação: os chassis batem
  { marca: 'RKT-8H42' },
  { fica: 'T06', ms: 600 },
  { naoVe: 'Confirmar o veículo', ms: 300 },
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'CHASSI LIDO DO VEÍCULO' },
  { ve: '9BM384067GB120401' },
  { ve: 'Os dois batem — é este veículo.' },
  { toca: 'Usar este ativo' },
  // a CAN lida
  { chega: 'T07' },
  { ve: 'RKT-8H42' },
  { ve: 'TENSÃO DA BATERIA' },
  { ve: 'de 12' },
  { toca: 'Configurar módulo' },
  // a cadeia grava e relê os blocos, um por segundo: Leitor → Eventos → Conexão
  { chega: 'T09' },
  { ve: 'Gravando · não interrompa' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', entre: [2000, 5000] },
  { ve: 'GRAVADO E RELIDO' },
  { ve: 'A12.G07.L02.E05.C03' },
  { ve: 'o módulo devolveu os seis blocos' },
  { toca: 'Voltar ao menu' },
  { chega: 'T04' },
  // a calibração do hodômetro: a foto do painel e o semear
  { toca: 'Calibração' },
  { chega: 'T10' },
  { ve: 'O MÓDULO CONTA' },
  { ve: '184.320' },
  { ve: 'aguarda' },
  { toca: 'Fotografar o painel' },
  { ve: 'fotografada' },
  { fica: 'T10', ms: 300 },
  { toca: 'Semear o hodômetro' },
  { chega: 'T10', momento: '01-momento-hodometro-semeado' },
  { ve: 'O MÓDULO CONTA AGORA' },
  { ve: 'relido às 14:30 · confere com o painel' },   // o 14:31 da referência é o desvio nomeado G9 (CHANGELOG)
  { ve: 'Calibrar o horímetro' },
  { toca: 'Voltar ao menu' },
  { chega: 'T04' },
  // o checklist: a Seção E abre o ciclo dinâmico
  { toca: 'Finalizar com checklist' },
  { chega: 'T13' },
  { ve: 'Faltam 9 itens' },
  { toca: 'E · Teste dinâmico' },
  { chega: 'T13', momento: '05-momento-e-teste-dinamico-aberta' },
  { toca: 'Ignição ligada' },
  // o ciclo dinâmico: a fila do módulo drena em 3 s, e o disparo acende
  { chega: 'T14' },
  { ve: 'FILA DRENANDO' },
  { ve: '6 mensagens e 2 de diagnóstico saindo do módulo' },
  { ve: 'de 5 passos' },
  { ve: '2 de 5 passos' },   // a semente traz 2 feitos (cicloPassosNaEntrada)
  { toca: 'Disparar evento de teste', entre: [2000, 4500] },
  // disparado (1 s real vale 4 s de prazo): o evento chega aos 24 s do prazo (6 s reais) e os
  // campos conferem aos 33 (8,25 s); os passos 3 a 5 acendem a +9, +12 e +15 s (T14·1)
  { ve: 'O EVENTO CHEGOU EM', entre: [5000, 7500] },
  { ve: '0:24' },
  { ve: '6 de 6', entre: [1000, 3500] },
  { ve: '3 de 5 passos', entre: [0, 1800] },
  { ve: '4 de 5 passos', entre: [2400, 3600] },
  { chega: 'T14', momento: '05-momento-ciclo-concluido', entre: [2400, 3600] },
  { ve: '5 de 5 passos' },
  { ve: '14:30:24' },
  // o checklist fecha: as fotos da Seção B, o Finalizar, o homologado
  { toca: 'Voltar ao checklist' },
  { chega: 'T13' },
  { ve: 'Faltam 4 itens' },
  { toca: 'B · Montagem' },
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  { toca: 'Módulo' },
  { chega: 'T13', momento: '07-momento-responder-item' },
  { ve: 'B · INSTALAÇÃO FÍSICA' },
  { ve: 'Módulo fixado e posicionado' },
  { ve: 'Depois: Antena GPS posicionada e livre' },
  { toca: 'Tirar foto' },
  { ve: 'Antena GPS posicionada e livre' },
  { toca: 'Tirar foto' },
  { ve: 'Chicote e emendas protegidos' },
  { toca: 'Tirar foto' },
  { ve: 'Leitor posicionado' },
  { toca: 'Tirar foto' },
  // sem próximo por fazer, volta à Seção B aberta: 5 de 5
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  { ve: 'B · Montagem' },
  { ve: '5 de 5' },
  { naoVe: 'Faltam' },
  { toca: 'Finalizar instalação' },
  { chega: 'T13', momento: '11-momento-homologado' },
  { ve: 'HOMOLOGADA' },
  { ve: '31 DE 31 CONFERIDOS' },
  { ve: 'RKT-8H42' },
  // ENCERRAR, depois de homologar: os sete passos, um a cada 600 ms, e o autoteste
  { toca: 'ENCERRAR' },
  { chega: 'T16' },
  { ve: 'Encerrar sessão' },
  { ve: 'Encerrando · não desconecte' },
  { ve: 'Contadores e estado' },
  { ve: 'Autoteste' },
  // fechado o sétimo passo, a faixa sobe e a tela passa pra Sessão encerrada
  { chega: 'T16', momento: '02-momento-sessao-encerrada', entre: [3000, 6000] },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { ve: 'Sessão encerrada' },
  // as oito assertivas acendem a 400 ms; a prova e o Voltar ao menu entram com a última
  { ve: 'A CONFIGURAÇÃO SOBREVIVEU AO REINÍCIO' },
  { ve: 'A12.G07.L02.E05.C03' },
  { ve: 'relido do módulo depois de desligar e ligar' },
  { ve: 'O ID na plataforma confirma quando a evidência subir.' },
  { toca: 'Voltar ao menu', entre: [2000, 5000] },
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  { ve: 'Sem sessão de configuração' },
  { naoVe: 'ENCERRAR' },
  { naoVe: 'RKT-8H42' },
  { ve: 'toque para procurar' },
  { fica: 'T04', ms: 600 },
]
