// C14 · o caminho do README: o começo do caminho do herói, do login à cadeia gravada,
// no ritmo de quem olha — cada toque espera um instante antes, pra quem vê o GIF
// acompanhar o dedo. É o que o README mostra no topo (GRAVA=… GRAVA_JANELA=1280x900,
// e o scripts/gif.py monta). Como roteiro, confere o mesmo que o heroi.mjs confere
// nesse trecho, e passa no `caminho.mjs todos` como os outros.
const olha = (ms = 900) => ({ dorme: ms })
export default [
  { abre: '' },
  { chega: 'T01', momento: null },
  { ve: '14:30' },
  olha(1200),
  { digita: 'Varzea26', em: 'SENHA' },
  olha(700),
  { toca: 'Entrar' },
  { desligado: 'Entrando…' },
  // a empresa vem sempre antes da unidade (decisão 37, revista)
  { chega: 'T02', momento: null },
  { ve: 'Pra qual empresa hoje?' },
  olha(),
  { marca: 'Viação Atlântico Sul' },
  olha(700),
  { toca: 'Ver as unidades' },
  { ve: 'Onde você está hoje?' },
  olha(),
  { marca: 'Garagem Várzea' },
  olha(700),
  { toca: 'Sincronizar Garagem Várzea' },
  { chega: 'T03' },
  { chega: 'T03', momento: '02-momento-concluido', entre: [3000, 6000] },
  olha(),
  { toca: 'Ir para o menu' },
  { chega: 'T04' },
  { ve: 'Seu acesso vence em 2 dias' },
  olha(1400),
  { toca: 'Entendi' },
  olha(),
  { toca: 'CONECTAR MÓDULO' },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  olha(),
  { marca: 'M2C-0417' },
  olha(700),
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  { ve: 'ENCERRAR', entre: [4000, 9000] },
  { ve: '11 de 11' },
  olha(1200),
  { toca: 'Selecionar ativo' },
  { chega: 'T06' },
  olha(),
  { marca: 'RKT-8H42' },
  olha(700),
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'Os dois batem — é este veículo.' },
  olha(1400),
  { toca: 'Usar este ativo' },
  { chega: 'T07' },
  { ve: 'TENSÃO DA BATERIA' },
  olha(4500),
  { toca: 'Configurar módulo' },
  { chega: 'T09' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', entre: [2000, 8000] },
  { ve: 'o módulo devolveu os seis blocos' },
  olha(2500),
]
