// C14 · o caminho do README: o começo do caminho do herói, do login à cadeia gravada,
// no ritmo de quem olha — cada toque espera um instante antes, pra quem vê o GIF
// acompanhar o dedo. É o que o README mostra no topo (GRAVA=… GRAVA_JANELA=1280x900,
// e o scripts/gif.py monta). Como roteiro, confere o mesmo que o heroi.mjs confere
// nesse trecho, e passa no `caminho.mjs todos` como os outros.
const olha = (ms = 900) => ({ dorme: ms })
export default [
  { abre: '' },
  { chega: 'T01', momento: null },
  { ouve: '9:30 · Wi-Fi, sinal e bateria' }, // pacote 4: a hora vem desenhada na barra oficial
  olha(1200),
  { digita: 'Varzea26', em: 'SENHA' },
  olha(700),
  { toca: 'Entrar' },
  { desligado: 'Entrando…' },
  // a empresa vem sempre antes da unidade (decisão 37, revista)
  { chega: 'T02', momento: null },
  { ve: 'Pra qual empresa hoje?' },
  olha(),
  { marca: 'Viação Atlântico Sul' },
  olha(700),
  { toca: 'Ver as unidades' },
  { ve: 'Onde você está hoje?' },
  olha(),
  { marca: 'Garagem Várzea' },
  olha(700),
  { toca: 'Sincronizar Garagem Várzea' },
  { chega: 'T03' },
  { chega: 'T03', momento: '02-momento-concluido', entre: [3000, 6000] },
  olha(),
  { toca: 'Ir para o menu' },
  { chega: 'T04' },
  { ve: 'Seu acesso vence em 2 dias' },
  olha(1400),
  { toca: 'Entendi' },
  olha(),
  { toca: 'CONECTAR MÓDULO' },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  olha(),
  { marca: 'M2C-0417' },
  olha(700),
  { toca: 'Conectar ao M2C-0417' },
  // o diagnóstico do módulo: as sete linhas acendem, e a faixa desce
  { chega: 'T07', momento: null },
  { ve: 'ENCERRAR', entre: [3500, 6500] },
  { ve: '8 de 8' },
  olha(1200),
  { toca: 'Selecionar ativo' },
  { chega: 'T06' },
  olha(),
  { marca: 'RKT-8H42' },
  olha(700),
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'O M2C-0417 fica neste ativo, na Viação Atlântico Sul.' },
  olha(1400),
  { toca: 'Vincular o módulo' },
  // o que vai ser gravado, e a cadeia
  { chega: 'T09', momento: '05-momento-o-que-vai-ser-gravado' },
  olha(1400),
  { toca: 'Gravar no módulo' },
  { chega: 'T09', momento: null },
  // (a rodada 1 do retorno do PM) a Conexão relida, o módulo confere que falou com o servidor
  { chega: 'T09', momento: '11-momento-conferindo-o-servidor', entre: [5000, 8500] },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', entre: [700, 1400] },
  { ve: '6 passos' },
  { ve: 'o módulo devolveu os seis passos' },
  olha(2500),
  // (o pacote 9) a CAN lida ao vivo: os sinais do motor ligado trocam o número a cada segundo
  { abre: '?tela=T07&momento=01-momento-can-lida' },
  { chega: 'T07', momento: '01-momento-can-lida' },
  { ve: 'Rotação' },
  olha(3600),
  // e o fim da visita: o encerramento, o autoteste e o traço do veredito se desenhando
  { abre: '?tela=T16' },
  { chega: 'T16', momento: '02-momento-instalacao-homologada', ms: 15000 },
  { ve: 'INSTALAÇÃO HOMOLOGADA' },
  olha(2500),
]
