// C11 · o recuperar acesso da T01 pela entrega de 24/09 (tela.md, decisões 31 e 32):
// o canal, o código, a folha "Não recebi o código" com a espera de 60 s, o reenvio
// com o prazo cheio de novo; noutra passada, o e-mail, o código certo, a senha nova,
// a senha alterada e o login.
const ATE_O_CODIGO = [
  { abre: '' },
  { chega: 'T01', momento: null },
  { toca: 'Esqueci a senha' },
  { chega: 'T01', momento: '02-momento-recuperar-escolher-canal' },
  { ve: 'RECUPERAR ACESSO' },
  { ve: 'Depois: o código · a nova senha' },
  { ve: '(81) •••••-8675' },
  { ve: 'r•••••@atlsul.com.br' },
  { ve: 'Vale por 10 minutos' },
  { ve: 'resta 1 envio nesta hora' },
  // o canal: tocar só marca (R-14); quem avança é o Enviar o código
  { marca: 'E-MAIL' },
  { fica: 'T01', ms: 400 },
  { chega: 'T01', momento: '02-momento-recuperar-escolher-canal' },
  { marca: 'MENSAGEM' },
  { fica: 'T01', ms: 400 },
  { chega: 'T01', momento: '02-momento-recuperar-escolher-canal' },
  { toca: 'Enviar o código' },
  { chega: 'T01', momento: '03-momento-recuperar-digitar-codigo' },
  { ve: 'Mandamos para (81) •••••-8675' },
  { ve: 'Digite o código' },
  { ve: 'VALE POR' },
  { ve: 'resta 1 envio nesta hora' },
  // a folha: as duas saídas esperam os 60 s do reenvio, com a contagem no lugar da seta
  { toca: 'Não recebi o código' },
  { chega: 'T01', momento: '04-momento-nao-recebi-o-codigo' },
  { ve: 'Conferir e reenviar' },
  { ve: 'Mandar para o e-mail' },
  { ve: '0:5' },
  // zerou com a folha aberta: a seta entra e as linhas acendem (a 11)
  { chega: 'T01', momento: '11-momento-nao-recebi-reenvio-liberado', ms: 70000, entre: [50000, 62000] },
  { naoVe: '0:0' },
]

export default [
  // 1ª passada: Conferir e reenviar → o código de novo, o prazo cheio, pro mesmo contato
  ...ATE_O_CODIGO,
  { toca: 'Conferir e reenviar' },
  { chega: 'T01', momento: '12-momento-codigo-reenviado' },
  { ve: 'Mandamos outro para (81) •••••-8675' },
  { ve: '10:00' },
  { ve: 'Reenviar em 60 s · este foi o último envio desta hora' },
  { ve: 'Reenviar em 59 s · este foi o último envio desta hora', entre: [500, 1600] },
  { naoVe: 'Conferir e reenviar' },
  // o reenvio chega com as células vazias: o Confirmar espera os seis dígitos (T01·6)
  { desligado: 'Confirmar' },
  // 2ª passada: Mandar para o e-mail → o código certo → a senha nova → senha alterada → o login
  ...ATE_O_CODIGO,
  { toca: 'Mandar para o e-mail' },
  { chega: 'T01', momento: '13-momento-codigo-no-e-mail' },
  { ve: 'Mandamos para r•••••@atlsul.com.br' },
  { ve: '10:00' },
  { ve: 'Reenviar em 60 s · este foi o último envio desta hora' },
  { desligado: 'Confirmar' },
  { digita: '48291', em: 'Digite o código' },
  { desligado: 'Confirmar' },
  { digita: '482913', em: 'Digite o código' },
  { toca: 'Confirmar' },
  { chega: 'T01', momento: '08-momento-recuperar-nova-senha' },
  { ve: '3 de 3' },
  { ve: 'Crie a nova senha' },
  { ve: 'Código conferido' },
  { ve: '482913' },
  { ve: '10 caracteres ou mais' },
  { ve: 'Diferente das 3 últimas' },
  { ve: 'confere ao salvar' },
  { toca: 'Salvar e entrar' },
  { chega: 'T01', momento: '09-momento-senha-alterada' },
  { ve: 'Senha alterada' },
  { ve: 'A senha nova já vale. Os outros aparelhos saíram da sua conta.' },
  { toca: 'Entrar com a senha nova' },
  // o login, com o usuário e a senha vazia
  { chega: 'T01', momento: null },
  { naoVe: 'Senha alterada' },
  { ve: 'Esqueci a senha' },
  // o Entrar diz o que falta enquanto o técnico apaga e digita, apagado e desabilitado
  // enquanto falta (a otimização do design): a senha vazia, Digite a senha; o usuário
  // apagado, Digite o usuário, com a senha ou sem ela; os dois, Entrar
  { desligado: 'Digite a senha' },
  { digita: 'r', em: 'USUÁRIO' },
  { tecla: 'Backspace' },
  { desligado: 'Digite o usuário' },
  { naoVe: 'Digite a senha' },
  { digita: 'Ibura', em: 'SENHA' },
  { desligado: 'Digite o usuário' },
  { digita: 'r.vieira', em: 'USUÁRIO' },
  { naoVe: 'Digite o usuário' },
  { naoVe: 'Digite a senha' },
  // com menos de 8, o erro: a senha apagada, o usuário fica (tela.md)
  { digita: 'Ibura27', em: 'SENHA' },
  { toca: 'Entrar' },
  { fica: 'T01', ms: 400 },
  { ve: 'USUÁRIO OU SENHA INCORRETOS' },
  { ve: 'Confira os dois e entre de novo.' },
  // no erro, o Entrar fica apagado, dizendo Digite a senha, até a senha ter um caractere (a 01, entrega de 25/09)
  { desligado: 'Digite a senha' },
  { digita: 'G', em: 'SENHA' },
  { naoVe: 'Digite a senha' },
  { ve: 'USUÁRIO OU SENHA INCORRETOS' },
  // o olho mostra e esconde: visível, o olho riscado e o nome Ocultar a senha (a 10)
  { digita: 'Garagem!Ibura27', em: 'SENHA' },
  { toca: 'Mostrar a senha' },
  { chega: 'T01', momento: '10-momento-senha-visivel' },
  { toca: 'Ocultar a senha' },
  { chega: 'T01', momento: null },
  { toca: 'Mostrar a senha' },
  { toca: 'Entrar' },
  { chega: 'T02' },
]
