// C11 · o voltar do Android (logica.md, "O voltar do Android"), nas 16 telas: no
// computador, o Esc. Cada tela abre pelo endereço (a semente) e pelos momentos que
// têm saída própria; o Esc faz o mesmo que o link de saída do rodapé (chega), ou
// não faz nada (fica): a tela sem saída desenhada, os processos que não podem
// parar, o diálogo sem X nem Cancelar e o estado aberto pela coluna do palco.
const esc = { tecla: 'Escape' }
export default [
  // ── T01 · na entrada, nada; em cada passo do recuperar, o Voltar ao login; na folha, o X ──
  { abre: '?tela=T01' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', momento: null },
  { ve: 'Esqueci a senha' },
  { abre: '?tela=T01&momento=02-momento-recuperar-escolher-canal' },
  esc,
  { chega: 'T01', momento: null },
  { ve: 'Esqueci a senha' },
  { abre: '?tela=T01&momento=04-momento-nao-recebi-o-codigo' },
  { ve: 'Conferir e reenviar' },
  esc,
  { chega: 'T01', momento: '03-momento-recuperar-digitar-codigo' },
  { naoVe: 'Conferir e reenviar' },
  esc,
  { chega: 'T01', momento: null },
  { abre: '?tela=T01&momento=08-momento-recuperar-nova-senha' },
  esc,
  { chega: 'T01', momento: null },
  // o diálogo Senha alterada não tem X nem Cancelar: o voltar não faz nada
  { abre: '?tela=T01&momento=09-momento-senha-alterada' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', momento: '09-momento-senha-alterada' },
  // um estado aberto pela coluna fica parado: o código expirado não volta ao login
  { abre: '?tela=T01&estado=06-estado-codigo-expirado' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '06-estado-codigo-expirado' },
  // o mundo real · o login sem conexão, pela coluna: parado e sem toque — o Entrar
  // que tenta de novo se prova no node (scripts/testar-login-e-bluetooth.mjs)
  { abre: '?tela=T01&estado=14-estado-login-sem-conexao' },
  { ve: 'SEM CONEXÃO' },
  { naoToca: 'Entrar' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '14-estado-login-sem-conexao' },

  // ── T02 · a escolha da garagem não tem saída desenhada: nada ──
  { abre: '?tela=T02' },
  esc,
  { fica: 'T02', ms: 500 },
  { abre: '?tela=T02&momento=01-momento-escolhida' },
  esc,
  { fica: 'T02', ms: 500 },
  { chega: 'T02', momento: '01-momento-escolhida' },
  // a busca sem resultado (03, a entrega de 25/09), no mundo do caso da lista longa: nada
  { abre: '?tela=T02&momento=03-momento-busca-sem-resultado' },
  esc,
  { fica: 'T02', ms: 500 },
  { chega: 'T02', momento: '03-momento-busca-sem-resultado' },

  // ── T03 · baixando, nada; no concluído, o Ir para o menu; na falha, o Voltar ao contexto ──
  { abre: '?tela=T03' },
  esc,
  { fica: 'T03', ms: 500 },
  { chega: 'T03', momento: null },
  { chega: 'T03', momento: '02-momento-concluido' },
  esc,
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  { abre: '?tela=T02' },
  { marca: 'Pátio Caruaru' },
  { toca: 'Sincronizar Pátio Caruaru' },
  { chega: 'T03' },
  { ve: 'A BAIXA PAROU ONDE ESTAVA' },
  esc,
  { chega: 'T02' },

  // ── T04 · no aviso do acesso, o Entendi (a semente também é chegada); no menu, nada;
  //    a folha fecha; o diálogo faz o Cancelar; o 12 aberto pela coluna fica parado ──
  { abre: '?tela=T04' },
  { ve: 'Seu acesso vence em 2 dias' },
  esc,
  { naoVe: 'Seu acesso vence em 2 dias' },
  { chega: 'T04', momento: null },
  esc,
  { fica: 'T04', ms: 500 },
  { chega: 'T04', momento: null },
  { naoVe: 'Seu acesso vence em 2 dias' },
  { toca: 'Conta' },
  { chega: 'T04', momento: '05-momento-folha-conta' },
  esc,
  { chega: 'T04', momento: null },
  { naoVe: 'Sair da conta' },
  { toca: 'Conta' },
  { toca: 'Sair da conta' },
  { chega: 'T04', momento: '06-momento-folha-conta-sair-com-sessao-aberta' },
  esc,
  { chega: 'T04', momento: '05-momento-folha-conta' },
  esc,
  { chega: 'T04', momento: null },
  // o endereço da folha abre a folha, e o aviso espera: o voltar fecha a folha, o aviso entra
  // depois de ela descer, e o voltar seguinte faz o Entendi
  { abre: '?tela=T04&momento=05-momento-folha-conta' },
  { naoVe: 'Seu acesso vence em 2 dias' },
  esc,
  { chega: 'T04', momento: null },
  { ve: 'Seu acesso vence em 2 dias' },
  esc,
  { naoVe: 'Seu acesso vence em 2 dias' },
  { chega: 'T04', momento: null },
  { abre: '?tela=T04&estado=12-estado-acesso-vencendo' },
  esc,
  { fica: 'T04', ms: 500 },
  { chega: 'T04', estado: '12-estado-acesso-vencendo' },
  { ve: 'Seu acesso vence em 2 dias' },

  // ── T05 · na busca, nada; a pré-checagem correndo, nada; aprovada, o Voltar ao menu;
  //    reprovada ou parada, o Procurar outro módulo, que volta à lista ──
  { abre: '?tela=T05' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', momento: null },
  { abre: '?tela=T05&momento=01-momento-nenhum-escolhido' },
  esc,
  { fica: 'T05', ms: 500 },
  { marca: 'M2C-0417' },
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  esc,
  { fica: 'T05', ms: 500 },
  { naoVe: 'ENCERRAR' },
  { ve: 'ENCERRAR' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T05&momento=01-momento-nenhum-escolhido' },
  { marca: 'M2C-0394' },
  { toca: 'Conectar ao M2C-0394' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  { ve: 'Procurar outro módulo' },
  esc,
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  { marca: 'M2C-0335' },
  { toca: 'Conectar ao M2C-0335' },
  { chega: 'T05', momento: '05-momento-pre-checagem' },
  { ve: 'Acordar módulo' },
  esc,
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  // o mundo real · o Bluetooth desligado e sem permissão, pela coluna: parados e sem
  // toque — o primário de cada um se prova no node (scripts/testar-login-e-bluetooth.mjs)
  { abre: '?tela=T05&estado=16-estado-bluetooth-desligado' },
  { ve: 'O Bluetooth está desligado' },
  { naoToca: 'Ligar o Bluetooth' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', estado: '16-estado-bluetooth-desligado' },
  { abre: '?tela=T05&estado=17-estado-bluetooth-sem-permissao' },
  { ve: 'Falta a permissão do Bluetooth' },
  { naoToca: 'Permitir' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', estado: '17-estado-bluetooth-sem-permissao' },

  // ── T06 · na lista, o Voltar ao menu; na confirmação, o Escolher outro ──
  { abre: '?tela=T06' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T06&momento=01-momento-confirmar-o-veiculo' },
  esc,
  { chega: 'T06', momento: null },
  { ve: 'Escolha o veículo que está na sua frente.' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T06&momento=07-momento-correcao-solicitada' },
  esc,
  { chega: 'T04' },
  // a trava sem link (04, fora do pacote): o Escolher outro do primário, de volta à lista
  // com a busca como estava — a placa não está no pacote, e é a busca sem resultado (08,
  // a entrega de 25/09); ali, o voltar é o Voltar ao menu, como na lista
  { abre: '?tela=T06' },
  { digita: 'ONK-8Q90', em: 'Buscar placa' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'FORA DO PACOTE DESTA UO' },
  esc,
  { chega: 'T06', momento: '08-momento-busca-sem-resultado' },
  { naoVe: 'FORA DO PACOTE DESTA UO' },
  { ve: 'Nada com “ONK-8Q90”' },
  esc,
  { chega: 'T04' },

  // ── T07 · tudo aprovado, o Voltar ao menu; com um sinal reprovado, nada ──
  { abre: '?tela=T07' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T06' },
  { marca: 'QJF-2C61' },
  { toca: 'Usar este ativo' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { toca: 'Usar este ativo' },
  { chega: 'T07' },
  { ve: 'Ler novamente' },
  esc,
  { fica: 'T07', ms: 500 },

  // ── T08 · antes e depois da releitura, o Voltar ao menu; relendo, nada ──
  { abre: '?tela=T08' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T08' },
  { toca: 'Refazer a leitura' },
  { chega: 'T08', momento: '01-momento-relendo' },
  esc,
  { fica: 'T08', ms: 500 },
  { chega: 'T08', momento: '01-momento-relendo' },
  { chega: 'T08', momento: '02-momento-concluida' },
  esc,
  { chega: 'T04' },

  // ── T09 · antes de a Conexão gravar, a recuperação; nela, nada; concluída, o Voltar ao menu ──
  { abre: '?tela=T09' },
  { ve: 'Gravando · não interrompa' },
  esc,
  { ve: 'Continuar a gravação' },
  { fica: 'T09', ms: 1500 },
  esc,
  { fica: 'T09', ms: 500 },
  { ve: 'Continuar a gravação' },
  { toca: 'Continuar a gravação' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida' },
  esc,
  { chega: 'T04' },

  // ── T10 · o Voltar ao menu, em todo passo; na câmera, o Voltar à calibração, sem foto;
  //    na calibração completa, sem link, o Concluir a calibração → o menu (decisão 33) ──
  { abre: '?tela=T10' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=05-momento-hodometro-digitado' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=06-momento-camera-do-painel' },
  { ve: 'Enquadre o hodômetro do painel' },
  esc,
  { chega: 'T10', momento: '05-momento-hodometro-digitado' },
  { toca: 'Fotografar o painel' },   // sem foto: o cartão continua a tirar
  { chega: 'T10', momento: '06-momento-camera-do-painel' },
  { toca: 'Voltar à calibração' },
  { chega: 'T10', momento: '05-momento-hodometro-digitado' },
  { desligado: 'Fotografe o painel' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=07-momento-painel-fotografado' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=01-momento-hodometro-semeado' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=08-momento-horimetro' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=09-momento-calibracao-completa' },
  { ve: 'Concluir a calibração' },
  esc,
  { chega: 'T04' },
  // o mundo real · a câmera sem a permissão, pela coluna: parada e sem toque — o
  // Abrir as configurações se prova no node (scripts/testar-camera.mjs)
  { abre: '?tela=T10&estado=11-estado-camera-sem-permissao' },
  { ve: 'O app precisa da câmera pra fotografar o painel' },
  { naoToca: 'Abrir as configurações' },
  { naoToca: 'Voltar à calibração' },
  esc,
  { fica: 'T10', ms: 500 },
  { chega: 'T10', estado: '11-estado-camera-sem-permissao' },

  // ── T11 · o que diverge, o Só registrar o diagnóstico; tudo confere, o Voltar ao menu ──
  { abre: '?tela=T11' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T11&momento=02-momento-tudo-confere' },
  esc,
  { chega: 'T04' },

  // ── T12 · na lista, o Voltar ao menu; no detalhe, o Voltar às instalações ──
  { abre: '?tela=T12' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T12&momento=01-momento-detalhe-da-instalacao' },
  esc,
  { chega: 'T12', momento: null },
  esc,
  { chega: 'T04' },

  // ── T13 · no mapa e na seção, o Voltar ao menu; no item, o Voltar ao checklist ──
  { abre: '?tela=T13' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&momento=02-momento-b-montagem-aberta' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&momento=07-momento-responder-item' },
  esc,
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  esc,
  { chega: 'T04' },

  // ── T14 · o Ir para o checklist; no ciclo concluído, o Voltar ao menu ──
  { abre: '?tela=T14' },
  esc,
  { chega: 'T13' },
  { abre: '?tela=T14&momento=05-momento-ciclo-concluido' },
  esc,
  { chega: 'T04' },

  // ── T15 · o Voltar ao menu; num estado da coluna, parado; com o painel aberto, o Esc é dele ──
  { abre: '?tela=T15' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T15&estado=01-estado-sem-erro' },
  esc,
  { fica: 'T15', ms: 500 },
  { chega: 'T15', estado: '01-estado-sem-erro' },
  { abre: '?tela=T15&painel=1' },
  esc,
  { fica: 'T15', ms: 500 },
  esc,
  { chega: 'T04' },

  // ── T16 · no encerramento e no autoteste, nada; encerrada, o Voltar ao menu ──
  { abre: '?tela=T16' },
  esc,
  { fica: 'T16', ms: 500 },
  { chega: 'T16', momento: null },
  { chega: 'T16', momento: '02-momento-sessao-encerrada' },
  esc,
  { fica: 'T16', ms: 3600 },
  esc,
  { chega: 'T04' },
  { ve: 'Sem sessão de configuração' },
  { abre: '?tela=T16&momento=03-momento-encerrando-sem-homologar' },
  esc,
  { fica: 'T16', ms: 500 },
  { chega: 'T16', momento: '03-momento-encerrando-sem-homologar' },
  { chega: 'T16', momento: '04-momento-encerrada-sem-homologar' },
  esc,
  { chega: 'T04' },
]
