// C11 · o voltar do Android (logica.md, "O voltar do Android"), em cada tela: no
// computador, o Esc. Cada tela abre pelo endereço (a semente) e pelos momentos que
// têm saída própria; o Esc faz o mesmo que o link de saída do rodapé (chega), ou
// não faz nada (fica): a tela sem saída desenhada, os processos que não podem
// parar, o diálogo sem X nem Cancelar e o estado aberto pela coluna do palco.
// O diálogo Encerrar antes de terminar? (decisão 36), no menu e por cima de outra
// tela, fecha pelo voltar, como o Continuar a instalação — antes da saída da tela.
const esc = { tecla: 'Escape' }
export default [
  // ── T01 · na entrada, nada; em cada passo do recuperar, o Voltar ao login; na folha, o X ──
  { abre: '?tela=T01' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', momento: null },
  { ve: 'Esqueci a senha' },
  { abre: '?tela=T01&momento=02-momento-recuperar-escolher-canal' },
  esc,
  { chega: 'T01', momento: null },
  { ve: 'Esqueci a senha' },
  { abre: '?tela=T01&momento=04-momento-nao-recebi-o-codigo' },
  { ve: 'Reenviar o código' },
  esc,
  { chega: 'T01', momento: '03-momento-recuperar-digitar-codigo' },
  { naoVe: 'Reenviar o código' },
  esc,
  { chega: 'T01', momento: null },
  { abre: '?tela=T01&momento=08-momento-recuperar-nova-senha' },
  esc,
  { chega: 'T01', momento: null },
  // o diálogo Senha alterada não tem X nem Cancelar: o voltar não faz nada
  { abre: '?tela=T01&momento=09-momento-senha-alterada' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', momento: '09-momento-senha-alterada' },
  // um estado aberto pela coluna fica parado: o código expirado não volta ao login
  { abre: '?tela=T01&estado=06-estado-codigo-expirado' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '06-estado-codigo-expirado' },
  // o mundo real · o login sem conexão, pela coluna: parado e sem toque — o Entrar
  // que tenta de novo se prova no node (scripts/testar-login-e-bluetooth.mjs)
  { abre: '?tela=T01&estado=14-estado-login-sem-conexao' },
  { ve: 'SEM CONEXÃO' },
  { naoToca: 'Entrar' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '14-estado-login-sem-conexao' },
  // a otimização do design · quem abre o app, pela coluna: parados e sem toque — o
  // que o Entrar diz e o xis se provam no node, e o xis também no roteiro lembrar.mjs
  { abre: '?tela=T01&estado=15-estado-primeiro-acesso' },
  { ve: 'Digite o usuário' },
  { naoToca: 'Digite o usuário' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '15-estado-primeiro-acesso' },
  { abre: '?tela=T01&estado=16-estado-usuario-lembrado' },
  { ve: 'Digite a senha' },
  { naoToca: 'Limpar o usuário' },
  esc,
  { fica: 'T01', ms: 500 },
  { chega: 'T01', estado: '16-estado-usuario-lembrado' },

  // ── T02 · a escolha da unidade não tem saída desenhada: nada — a 00 e o 01, de uma
  //    empresa só. Nas empresas do herói (o 07), nada; nas unidades dele (o 09), o
  //    Trocar de empresa, a saída desenhada do rodapé (padrão c, confirmado) ──
  { abre: '?tela=T02' },
  esc,
  { fica: 'T02', ms: 500 },
  { abre: '?tela=T02&momento=01-momento-escolhida' },
  esc,
  { fica: 'T02', ms: 500 },
  { chega: 'T02', momento: '01-momento-escolhida' },
  { abre: '?tela=T02&momento=07-momento-empresa-escolhida' },
  esc,
  { fica: 'T02', ms: 500 },
  { chega: 'T02', momento: '07-momento-empresa-escolhida' },
  { abre: '?tela=T02&momento=09-momento-unidade-escolhida-com-trocar-empresa' },
  esc,
  { chega: 'T02', momento: '07-momento-empresa-escolhida' },
  { ve: 'Pra qual empresa hoje?' },
  // a busca sem resultado (03, a entrega de 25/09), no mundo do caso da lista longa: nada
  { abre: '?tela=T02&momento=03-momento-busca-sem-resultado' },
  esc,
  { fica: 'T02', ms: 500 },
  { chega: 'T02', momento: '03-momento-busca-sem-resultado' },

  // ── T03 · baixando, nada; no concluído, o Ir para o menu; na falha, o Voltar ao contexto ──
  { abre: '?tela=T03' },
  esc,
  { fica: 'T03', ms: 500 },
  { chega: 'T03', momento: null },
  { chega: 'T03', momento: '02-momento-concluido' },
  esc,
  { chega: 'T04', momento: '01-momento-sem-modulo' },
  { abre: '?tela=T02' },
  { marca: 'Pátio Caruaru' },
  { toca: 'Sincronizar Pátio Caruaru' },
  { chega: 'T03' },
  { ve: 'A BAIXA PAROU ONDE ESTAVA' },
  esc,
  { chega: 'T02' },

  // ── T04 · no aviso do acesso, o Entendi (a semente também é chegada); no menu, nada;
  //    a folha fecha; o diálogo faz o Cancelar; o 12 aberto pela coluna fica parado ──
  { abre: '?tela=T04' },
  { ve: 'Seu acesso vence em 2 dias' },
  esc,
  { naoVe: 'Seu acesso vence em 2 dias' },
  { chega: 'T04', momento: null },
  esc,
  { fica: 'T04', ms: 500 },
  { chega: 'T04', momento: null },
  { naoVe: 'Seu acesso vence em 2 dias' },
  { toca: 'Conta' },
  { chega: 'T04', momento: '05-momento-folha-conta' },
  esc,
  { chega: 'T04', momento: null },
  { naoVe: 'Sair da conta' },
  { toca: 'Conta' },
  { toca: 'Sair da conta' },
  { chega: 'T04', momento: '06-momento-folha-conta-sair-com-sessao-aberta' },
  esc,
  { chega: 'T04', momento: '05-momento-folha-conta' },
  esc,
  { chega: 'T04', momento: null },
  // o endereço da folha abre a folha, e o aviso espera: o voltar fecha a folha, o aviso entra
  // depois de ela descer, e o voltar seguinte faz o Entendi
  { abre: '?tela=T04&momento=05-momento-folha-conta' },
  { naoVe: 'Seu acesso vence em 2 dias' },
  esc,
  { chega: 'T04', momento: null },
  { ve: 'Seu acesso vence em 2 dias' },
  esc,
  { naoVe: 'Seu acesso vence em 2 dias' },
  { chega: 'T04', momento: null },
  { abre: '?tela=T04&estado=12-estado-acesso-vencendo' },
  esc,
  { fica: 'T04', ms: 500 },
  { chega: 'T04', estado: '12-estado-acesso-vencendo' },
  { ve: 'Seu acesso vence em 2 dias' },
  // o diálogo do ENCERRAR antes de homologar (13): o voltar faz o Continuar a instalação,
  // e o aviso do acesso, que esperava o menu ficar sem nada por cima, entra depois
  { abre: '?tela=T04&momento=13-momento-encerrar-antes-de-homologar' },
  { ve: 'Encerrar antes de terminar?' },
  { naoVe: 'Seu acesso vence em 2 dias' },
  esc,
  { chega: 'T04', momento: null },
  { naoVe: 'Encerrar antes de terminar?' },
  { ve: 'Seu acesso vence em 2 dias' },
  esc,
  { naoVe: 'Seu acesso vence em 2 dias' },
  { toca: 'ENCERRAR' },
  { chega: 'T04', momento: '13-momento-encerrar-antes-de-homologar' },
  esc,
  { chega: 'T04', momento: null },
  // a folha com o Trocar de empresa (14), pela coluna: parada e sem toque — o toque se
  // anda na folha do herói, no fluxo (empresa.mjs), e se prova no node (testar-trocar-empresa.mjs)
  { abre: '?tela=T04&estado=14-estado-folha-trocar-de-unidade-com-empresa' },
  { ve: 'Trocar de unidade' },
  { ve: 'Trocar de empresa' },
  { naoToca: 'Trocar de empresa' },
  esc,
  { fica: 'T04', ms: 500 },
  { chega: 'T04', estado: '14-estado-folha-trocar-de-unidade-com-empresa' },

  // ── T05 · na busca e na lista, nada: a T05 só conecta (pacote 1), e a conexão abre o
  //    diagnóstico (T07, abaixo) ──
  { abre: '?tela=T05' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', momento: null },
  { abre: '?tela=T05&momento=01-momento-nenhum-escolhido' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  // o mundo real · o Bluetooth desligado e sem permissão, pela coluna: parados e sem
  // toque — o primário de cada um se prova no node (scripts/testar-login-e-bluetooth.mjs)
  { abre: '?tela=T05&estado=16-estado-bluetooth-desligado' },
  { ve: 'O Bluetooth está desligado' },
  { naoToca: 'Ligar o Bluetooth' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', estado: '16-estado-bluetooth-desligado' },
  { abre: '?tela=T05&estado=17-estado-bluetooth-sem-permissao' },
  { ve: 'Falta a permissão do Bluetooth' },
  { naoToca: 'Permitir' },
  esc,
  { fica: 'T05', ms: 500 },
  { chega: 'T05', estado: '17-estado-bluetooth-sem-permissao' },

  // ── T06 · na lista, o Voltar ao menu; na confirmação, o Escolher outro ──
  { abre: '?tela=T06' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T06&momento=01-momento-confirmar-o-veiculo' },
  esc,
  { chega: 'T06', momento: null },
  { ve: 'Escolha o veículo que está na sua frente.' },
  esc,
  { chega: 'T04' },
  // a trava sem link (04, fora do pacote): o Escolher outro do primário, de volta à lista
  // com a busca como estava — a placa não está no pacote, e é a busca sem resultado (08,
  // a entrega de 25/09); ali, o voltar é o Voltar ao menu, como na lista
  { abre: '?tela=T06' },
  { digita: 'ONK-8Q90', em: 'Buscar placa' },
  { chega: 'T06', momento: '01-momento-confirmar-o-veiculo' },
  { ve: 'FORA DO PACOTE DESTA UO' },
  esc,
  { chega: 'T06', momento: '08-momento-busca-sem-resultado' },
  { naoVe: 'FORA DO PACOTE DESTA UO' },
  { ve: 'Nada com “ONK-8Q90”' },
  esc,
  { chega: 'T04' },

  // ── T07 · o diagnóstico (pacote 1): lendo, nada; passou sem trava, o Voltar ao menu; na
  //    trava, o Procurar outro módulo, que volta à lista; atualizando e relendo, nada; com a
  //    CAN lida, o Voltar ao menu ──
  { abre: '?tela=T07' },
  esc,
  { chega: 'T04' },
  // com o diálogo do ENCERRAR por cima, o voltar fecha só o diálogo, e a T07 fica
  { abre: '?tela=T07' },
  { toca: 'ENCERRAR' },
  { ve: 'Encerrar antes de terminar?' },
  esc,
  { naoVe: 'Encerrar antes de terminar?' },
  { fica: 'T07', ms: 500 },
  esc,
  { chega: 'T04' },
  // a leitura que corre, da conexão: nada; as sete passam, e o voltar é o Voltar ao menu
  { abre: '?tela=T05&momento=01-momento-nenhum-escolhido' },
  { marca: 'M2C-0417' },
  { toca: 'Conectar ao M2C-0417' },
  { chega: 'T07', momento: null },
  esc,
  { fica: 'T07', ms: 500 },
  { naoVe: 'ENCERRAR' },
  { ve: 'ENCERRAR', ms: 8000 },
  { ve: 'Selecionar ativo' },
  esc,
  { chega: 'T04' },
  // a trava (o M2C-0999, fora do cadastro): lendo, nada; parada, o Procurar outro módulo
  { abre: '?tela=T05&momento=01-momento-nenhum-escolhido' },
  { marca: 'M2C-0999' },
  { toca: 'Conectar ao M2C-0999' },
  { chega: 'T07', momento: null },
  esc,
  { fica: 'T07', ms: 300 },
  { ve: 'Procurar outro módulo', ms: 8000 },
  esc,
  { chega: 'T05', momento: '01-momento-nenhum-escolhido' },
  { desligado: 'Conectar' },
  // o firmware que atualiza (06): nada
  { abre: '?tela=T07&momento=06-momento-atualizando-o-firmware' },
  esc,
  { fica: 'T07', ms: 300 },
  // a CAN lida (01): o Ler de novo relê (10), e relendo, nada; lida de novo, o Voltar ao menu
  { abre: '?tela=T07&momento=01-momento-can-lida' },
  { toca: 'Ler de novo' },
  { chega: 'T07', momento: '10-momento-relendo-a-can' },
  esc,
  { fica: 'T07', ms: 500 },
  { chega: 'T07', momento: '01-momento-can-lida', ms: 8000 },
  esc,
  { chega: 'T04' },

  // ── T09 · antes de gravar (05), o Voltar ao menu; gravando, antes de a Conexão gravar, a
  //    recuperação; nela, nada; concluída, o Voltar ao menu ──
  { abre: '?tela=T09' },
  { chega: 'T09', momento: '05-momento-o-que-vai-ser-gravado' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T09' },
  { toca: 'Gravar no módulo' },
  { chega: 'T09', momento: null },
  { ve: 'Gravando · não interrompa' },
  esc,
  { ve: 'Continuar a gravação' },
  { fica: 'T09', ms: 1500 },
  esc,
  { fica: 'T09', ms: 500 },
  { ve: 'Continuar a gravação' },
  { toca: 'Continuar a gravação' },
  { chega: 'T09', momento: '04-momento-cadeia-concluida', ms: 12000 },
  esc,
  { chega: 'T04' },

  // ── T10 · o Voltar ao menu, em todo passo — também onde o link do rodapé é o Pular o horímetro
  //    (08: o voltar nunca pula); no semear, nada (a decisão do diretor de 25/09: o semear
  //    não para); na calibração completa, o Voltar ao menu, embaixo do Fazer o ciclo de testes ──
  { abre: '?tela=T10' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=05-momento-hodometro-digitado' },
  esc,
  { chega: 'T04' },
  // o semear grava no módulo e não para: nos 2 s, o Voltar ao menu desabilitado e o Esc, nada;
  // o ENCERRAR faz o mesmo que o voltar, apagado (a lei 17)
  { abre: '?tela=T10&momento=05-momento-hodometro-digitado' },
  { toca: 'Semear o hodômetro' },
  { desligado: 'Gravando no módulo…' },
  { desligado: 'Voltar ao menu' },
  { desligado: 'ENCERRAR' },
  esc,
  { fica: 'T10', ms: 300 },
  { desligado: 'Relendo…', entre: [300, 1500] },
  { desligado: 'Voltar ao menu' },
  { desligado: 'ENCERRAR' },
  esc,
  { fica: 'T10', ms: 300 },
  { chega: 'T10', momento: '01-momento-hodometro-semeado', entre: [0, 1500] },
  { ve: 'O MÓDULO CONTA AGORA' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=01-momento-hodometro-semeado' },
  { ve: 'Calibrar a rotação' },   // a rodada 2: o caminhão coletor, com a rotação ainda por calibrar
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=08-momento-horimetro' },
  { ve: 'Pular o horímetro' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=09-momento-calibracao-completa' },
  { ve: 'Fazer o ciclo de testes' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T10&momento=09-momento-calibracao-completa' },
  { toca: 'Voltar ao menu' },
  { chega: 'T04' },

  // ── T11 · o que diverge, nada: o link é o Outras ações, que não sai da tela (a última
  //    entrega, decisão 40); na folha Outras ações, fecha; tudo confere, o Voltar ao menu ──
  { abre: '?tela=T11' },
  esc,
  { fica: 'T11', ms: 500 },
  { chega: 'T11', momento: null },
  { abre: '?tela=T11&momento=03-momento-outras-acoes' },
  { ve: 'Apenas registrar o diagnóstico' },
  esc,
  { chega: 'T11', momento: null },
  { naoVe: 'Apenas registrar o diagnóstico' },
  esc,
  { fica: 'T11', ms: 500 },
  { chega: 'T11', momento: null },
  { abre: '?tela=T11&momento=02-momento-tudo-confere' },
  esc,
  { chega: 'T04' },

  // ── T12 · na lista, o Voltar ao menu; no detalhe, o Voltar às instalações ──
  { abre: '?tela=T12' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T12&momento=01-momento-detalhe-da-instalacao' },
  esc,
  { chega: 'T12', momento: null },
  esc,
  { chega: 'T04' },

  // ── T13 · nas seções e no registrado (aguardando autoteste), o Voltar ao menu; no item, o Voltar ao checklist ──
  { abre: '?tela=T13' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&momento=02-momento-b-montagem-aberta' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&momento=07-momento-responder-item' },
  esc,
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  esc,
  { chega: 'T04' },
  // o problema fotografado (15, decisão 39) também é o nível do item: o Voltar ao checklist
  { abre: '?tela=T13&momento=15-momento-problema-fotografado' },
  esc,
  { chega: 'T13', momento: '02-momento-b-montagem-aberta' },
  esc,
  { chega: 'T04' },
  // a estrutura nova (decisão 34): a E resolvida e o registrado fazem o Voltar ao menu (a rodada 1: o checklist registrado, aguardando autoteste); o sem localização é da coluna, parado
  { abre: '?tela=T13&momento=13-momento-e-resolvida' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&momento=11-momento-aguardando-autoteste' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T13&estado=14-estado-aguardando-autoteste-sem-localizacao' },
  esc,
  { fica: 'T13', ms: 500 },
  { chega: 'T13', estado: '14-estado-aguardando-autoteste-sem-localizacao' },

  // ── T14 · o Ir para o checklist; no ciclo concluído, o Voltar ao menu ──
  { abre: '?tela=T14' },
  esc,
  { chega: 'T13' },
  { abre: '?tela=T14&momento=05-momento-ciclo-concluido' },
  esc,
  { chega: 'T04' },

  // ── T15 · o Voltar ao menu; num estado da coluna, parado; com o painel aberto, o Esc é dele ──
  { abre: '?tela=T15' },
  esc,
  { chega: 'T04' },
  { abre: '?tela=T15&estado=01-estado-sem-erro' },
  esc,
  { fica: 'T15', ms: 500 },
  { chega: 'T15', estado: '01-estado-sem-erro' },
  { abre: '?tela=T15&painel=1' },
  esc,
  { fica: 'T15', ms: 500 },
  esc,
  { chega: 'T04' },

  // ── T16 · no encerramento e no autoteste, nada; encerrada, o Voltar ao menu ──
  { abre: '?tela=T16' },
  esc,
  { fica: 'T16', ms: 500 },
  { chega: 'T16', momento: null },
  { chega: 'T16', momento: '07-momento-autoteste-correndo' },
  esc,
  { fica: 'T16', ms: 1500 },
  { chega: 'T16', momento: '02-momento-instalacao-homologada' },
  esc,
  { chega: 'T04' },
  { ve: 'Sem sessão de configuração' },
  { abre: '?tela=T16&momento=03-momento-encerrando-sem-homologar' },
  esc,
  { fica: 'T16', ms: 500 },
  { chega: 'T16', momento: '03-momento-encerrando-sem-homologar' },
  { chega: 'T16', momento: '04-momento-encerrada-sem-homologar' },
  esc,
  { chega: 'T04' },
]
